### ISSUE TITLE
Allow for nodes to be different colours.

### ISSUE THREAD

**Issue by bhouston** [beeglebug/behave-flow#1]
In UE Blueprints nodes with different purposes have different colours.  We should likely support the same.  I think you can not completely infer the purpose so instead we should just allow for nodes to either assign themselves colors or assign themselves roles which map onto colors.

**Comment by beeglebug** [comment]
Could we possibly use the group names? Ie action/state/logic

**Comment by bhouston** [comment]
I added a field to the nodes called "Category" that has the main categories that Unreal engine uses.  You can read this from the node specs that can now be exported.

**Comment by beeglebug** [comment]
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/954416/182935885-3e7488c6-f899-4bc0-ba25-d89b4d03c1a4.png">
no logic yet, but playing around with the nodes having colours and building a palette

**Comment by bhouston** [comment]
Nice!  I would totally suggest following the Unreal Engine Blueprints color scheme, it is the most familiar in the industry:

* Events: Red
* Logic: Green
* Constants: Purple
* Actions: Blue
* Flow/Time: Grey

Source: https://docs.unrealengine.com/4.26/en-US/ProgrammingAndScripting/Blueprints/UserGuide/Nodes/

They also have colors for the socket types (both the socket icon as well as the line that connects them).
* Flow - White
* Number - Green.
* Boolean - Red
* String - Purple

Source: https://docs.unrealengine.com/4.26/en-US/ProgrammingAndScripting/Blueprints/BP_HowTo/ConnectingNodes/

**Comment by beeglebug** [comment]
Node colours are now driven from categories, but I'm going to leave this open until socket handles are done

**Comment by beeglebug** [comment]
socket handle colors are now working
