### ISSUE TITLE
More than one input to a parameter socket shouldn't be allowed.

### ISSUE THREAD

**Issue by bhouston** [beeglebug/behave-flow#13]
This graph no longer makes any sense:

![Screenshot 2022-10-10 at 7 31 54 PM](https://user-images.githubusercontent.com/588541/194967343-2042776e-18f3-4a7d-9a6a-53eb13e63395.png)

So it should be prevented from the UI.

**Comment by beeglebug** [comment]
fixed by 5bb64b3
