### ISSUE TITLE
If a "flow" socket's name isn't "flow" we should show the name, helps with For Loops.

### ISSUE THREAD

**Issue by bhouston** [beeglebug/behave-flow#14]
If there is more than one flow socket on import or output, we should display the names.

For example with For Loop here, the first flow output is "loopBody" which fires each time there is an iteration and then there is a second flow output "completed" flow socket that fires once the for loop is complete.

Right now usability is impairs because there are no labels, see here:

![Screenshot 2022-10-10 at 7 33 13 PM](https://user-images.githubusercontent.com/588541/194967489-30e15d5f-88f2-4fa1-bcb2-b4af2d2b4cbd.png)

**Comment by beeglebug** [comment]
fixed by 7e803c2
